#!/usr/bin/env bash
# we're displaying 1 to 100
y=1
while [ "$y" -le 100 ]; do
if ! (( y % 3 )) && ! (( y % 5 )); then
echo "FizzBuzz"
elif ! (( y % 3 )); then
echo "Fizz"
elif ! (( y % 5 )); then
echo "Buzz"
else
echo "$y"
fi
((y++))
done
