#!/usr/bin/env bash
#we are doing number 4, 8 is my chance
i=1
while [ "$i" -lt 11 ]; do
if [[ $i -eq 4 ]]; then
echo "bad luck"
elif [[ $i -eq 8 ]]; then
echo "good luck"
else
echo "Best School"
fi((i++))
done
